//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AigioL.Common.AspNetCore.AppCenter.Identity.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AigioL.Common.AspNetCore.AppCenter.Identity.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败，此账号已被其他用户绑定 的本地化字符串。
        /// </summary>
        public static string BindFail_UserIsNotNull {
            get {
                return ResourceManager.GetString("BindFail_UserIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要开启 JavaScript 才能浏览本站点。 的本地化字符串。
        /// </summary>
        public static string BodyNoScript {
            get {
                return ResourceManager.GetString("BodyNoScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，您正在使用一个过时的浏览器。建议升级您的浏览器或使用 的本地化字符串。
        /// </summary>
        public static string BrowserIsSupported1 {
            get {
                return ResourceManager.GetString("BrowserIsSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等其他现代浏览器，以提高您的体验。 的本地化字符串。
        /// </summary>
        public static string BrowserIsSupported2 {
            get {
                return ResourceManager.GetString("BrowserIsSupported2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 NameIdentifier 失败，值：{0}，渠道：{1}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ClaimTypes_NameIdentifier_IsNull__ {
            get {
                return ResourceManager.GetString("ClaimTypes_NameIdentifier_IsNull__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击此处重试 的本地化字符串。
        /// </summary>
        public static string ClickHereTryAgain {
            get {
                return ResourceManager.GetString("ClickHereTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #2196F3 的本地化字符串。
        /// </summary>
        public static string ColorPrimary {
            get {
                return ResourceManager.GetString("ColorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点此复制 的本地化字符串。
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该浏览器不支持点击复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string CopyNoSupport {
            get {
                return ResourceManager.GetString("CopyNoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来自第三方登录提供程序的错误，{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ErrorFromExternalProvider_ {
            get {
                return ResourceManager.GetString("ErrorFromExternalProvider_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的第三方登录提供程序，{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ErrorFromUnknownAuthType_ {
            get {
                return ResourceManager.GetString("ErrorFromUnknownAuthType_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的第三方登录渠道，{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ErrorFromUnknownChannel_ {
            get {
                return ResourceManager.GetString("ErrorFromUnknownChannel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载第三方登录信息时出错，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ErrorLoadingExternalLoginInfo {
            get {
                return ResourceManager.GetString("ErrorLoadingExternalLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速登录错误 {0} 的本地化字符串。
        /// </summary>
        public static string ExternalLoginError_ {
            get {
                return ResourceManager.GetString("ExternalLoginError_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速登录仅可在未授权时使用，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string IsBindFalseUserIsNotNull {
            get {
                return ResourceManager.GetString("IsBindFalseUserIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号绑定获取当前登录用户失败，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string IsBindTrueUserIsNull {
            get {
                return ResourceManager.GetString("IsBindTrueUserIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login2 {
            get {
                return ResourceManager.GetString("Login2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 / 注册 的本地化字符串。
        /// </summary>
        public static string LoginAndRegister {
            get {
                return ResourceManager.GetString("LoginAndRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1}已完成，您可以关闭此窗口并返回至 {2}。 的本地化字符串。
        /// </summary>
        public static string LoginSuccessTip1___ {
            get {
                return ResourceManager.GetString("LoginSuccessTip1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此浏览器窗口/标签页将会在 10 秒内尝试自动关闭，您也可以手动关闭。 的本地化字符串。
        /// </summary>
        public static string LoginSuccessTip2 {
            get {
                return ResourceManager.GetString("LoginSuccessTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长时间未跳转？ 的本地化字符串。
        /// </summary>
        public static string LongTimeNoJump {
            get {
                return ResourceManager.GetString("LongTimeNoJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接程序出错，请手动复制以下内容到程序点击手动登录。 的本地化字符串。
        /// </summary>
        public static string ManualCopyTip {
            get {
                return ResourceManager.GetString("ManualCopyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 width=1024;height=768 的本地化字符串。
        /// </summary>
        public static string MetaMSApplicationWindow {
            get {
                return ResourceManager.GetString("MetaMSApplicationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误! 的本地化字符串。
        /// </summary>
        public static string ModelErrorTitle {
            get {
                return ResourceManager.GetString("ModelErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}成功! 的本地化字符串。
        /// </summary>
        public static string ModelSuccessTitle_ {
            get {
                return ResourceManager.GetString("ModelSuccessTitle_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用户{0} 的本地化字符串。
        /// </summary>
        public static string NewUserNickName_ {
            get {
                return ResourceManager.GetString("NewUserNickName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查是否能正常访问 Steam 社区。 的本地化字符串。
        /// </summary>
        public static string PleaseCheckSteamCommunity {
            get {
                return ResourceManager.GetString("PleaseCheckSteamCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后… 的本地化字符串。
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 OpenId 失败，值：{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ReadFailByOpenId_ {
            get {
                return ResourceManager.GetString("ReadFailByOpenId_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 SteamAccountId64 失败，值：{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ReadFailBySteamAccountId64_ {
            get {
                return ResourceManager.GetString("ReadFailBySteamAccountId64_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 UnionId 失败，值：{0}，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string ReadFailByUnionId_ {
            get {
                return ResourceManager.GetString("ReadFailByUnionId_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前 Steam 登录的请求过多请刷新页面重试或稍后再试 的本地化字符串。
        /// </summary>
        public static string SteamLoginException {
            get {
                return ResourceManager.GetString("SteamLoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.google.cn/chrome/browser/desktop 的本地化字符串。
        /// </summary>
        public static string Url_Chrome {
            get {
                return ResourceManager.GetString("Url_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.mozilla.org/firefox/browsers 的本地化字符串。
        /// </summary>
        public static string Url_Firefox {
            get {
                return ResourceManager.GetString("Url_Firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.microsoft.com/edge 的本地化字符串。
        /// </summary>
        public static string Url_MicrosoftEdge {
            get {
                return ResourceManager.GetString("Url_MicrosoftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与程序的连接丢失，点击重试或重新在程序内点击快速登录。 的本地化字符串。
        /// </summary>
        public static string WebSocketLostTip {
            get {
                return ResourceManager.GetString("WebSocketLostTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号必须为 UInt16 类型，请联系网站管理员。 的本地化字符串。
        /// </summary>
        public static string WebSocketPortIsNotUInt16 {
            get {
                return ResourceManager.GetString("WebSocketPortIsNotUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码获取次数达到今日上限了哦，明天再试试吧 的本地化字符串。
        /// </summary>
        public static string 当前手机号今日发送短信数量超过最大上限 {
            get {
                return ResourceManager.GetString("当前手机号今日发送短信数量超过最大上限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作有点频繁哦，{0}分钟以后再试试吧 的本地化字符串。
        /// </summary>
        public static string 当前手机号发送短信过于频繁_ {
            get {
                return ResourceManager.GetString("当前手机号发送短信过于频繁_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前手机号码不存在 的本地化字符串。
        /// </summary>
        public static string 当前手机号码不存在 {
            get {
                return ResourceManager.GetString("当前手机号码不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个手机号已经被使用了哦 的本地化字符串。
        /// </summary>
        public static string 手机号码已存在 {
            get {
                return ResourceManager.GetString("手机号码已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个手机号已经被绑定了哦 的本地化字符串。
        /// </summary>
        public static string 手机号码已存在_换绑手机 {
            get {
                return ResourceManager.GetString("手机号码已存在_换绑手机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个手机号已经被注册了哦 的本地化字符串。
        /// </summary>
        public static string 手机号码已存在_注册 {
            get {
                return ResourceManager.GetString("手机号码已存在_注册", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作太频繁，请稍后再试 的本地化字符串。
        /// </summary>
        public static string 操作太频繁请稍后再试 {
            get {
                return ResourceManager.GetString("操作太频繁请稍后再试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新手机号不能与旧手机号一样 的本地化字符串。
        /// </summary>
        public static string 新手机号不能与旧手机号一样 {
            get {
                return ResourceManager.GetString("新手机号不能与旧手机号一样", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法登录客服账户 的本地化字符串。
        /// </summary>
        public static string 无法登录客服账户 {
            get {
                return ResourceManager.GetString("无法登录客服账户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的 IP 地址 的本地化字符串。
        /// </summary>
        public static string 未知的IP地址 {
            get {
                return ResourceManager.GetString("未知的IP地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        public static string 用户不存在 {
            get {
                return ResourceManager.GetString("用户不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信服务已停用 的本地化字符串。
        /// </summary>
        public static string 短信服务已停用 {
            get {
                return ResourceManager.GetString("短信服务已停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信服务已停用，请使用快速登录进行登录或注册 的本地化字符串。
        /// </summary>
        public static string 短信服务已停用_登录或注册 {
            get {
                return ResourceManager.GetString("短信服务已停用_登录或注册", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端错误 5001 - 短信服务 的本地化字符串。
        /// </summary>
        public static string 短信服务故障 {
            get {
                return ResourceManager.GetString("短信服务故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信验证码不正确 的本地化字符串。
        /// </summary>
        public static string 短信验证码不正确 {
            get {
                return ResourceManager.GetString("短信验证码不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该邮箱已被其它用户使用 的本地化字符串。
        /// </summary>
        public static string 该邮箱已被其它用户使用 {
            get {
                return ResourceManager.GetString("该邮箱已被其它用户使用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误 的本地化字符串。
        /// </summary>
        public static string 账号或密码错误 {
            get {
                return ResourceManager.GetString("账号或密码错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证方式错误 的本地化字符串。
        /// </summary>
        public static string 验证方式错误 {
            get {
                return ResourceManager.GetString("验证方式错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确 的本地化字符串。
        /// </summary>
        public static string 验证码不正确 {
            get {
                return ResourceManager.GetString("验证码不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误或已过期 的本地化字符串。
        /// </summary>
        public static string 验证码已过期或不存在 {
            get {
                return ResourceManager.GetString("验证码已过期或不存在", resourceCulture);
            }
        }
    }
}
